server {
    listen 80;
    server_name localhost;

    location / {
        root D:/TerraCarbon;
        index dashboard.html;
    }

    location /terraform_outputs.json {
        root D:/TerraCarbon;
    }

    location /token.json {
        root D:/TerraCarbon;
        allow 127.0.0.1;
        deny all;
    }

    location /api/cost/ {
        proxy_pass https://management.azure.com/;
        proxy_set_header Host management.azure.com;
        proxy_set_header Authorization "Bearer $http_x_azure_token";
        proxy_pass_request_headers on;
    }

    location /api/logs/ {
        proxy_pass https://api.loganalytics.io/;
        proxy_set_header Host api.loganalytics.io;
        proxy_set_header Authorization "Bearer $http_x_azure_token";
        proxy_pass_request_headers on;
    }
}
